# Generated by Django 5.0.4 on 2024-05-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episode',
            new_name='Episodio',
        ),
    ]
