# Generated by Django 5.0.4 on 2024-04-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cas_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
